language: python

services:
  - postgresql

python:
  - "3.3"
  - "2.7"

env:
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.1

branches:
  only:
    - master

before_script:
    - psql -c 'create database test;' -U postgres

# command to install requirements
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -r requirements.txt --use-mirrors

# command to run tests, e.g. python setup.py test
script:
  - python runtests.py

after_success:
  coveralls
