from api_tests import *
from cluster_id_tests import *
from cluster_tests import *
from conf_tests import *
from conf_err_tests import *
from dispatcher_tests import *
from dispatcher_conf_tests import *
from provider_tests import *
from quotas_tests import *
from selectors_tests import *
from util_tests import *
from version_tests import *
from views_tests import *